logo: "/images/dodobird.png"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
url: "https://testdodo.github.io/"
baseurl: "/testdodo"
permalink: pretty
heading_anchors: true

---
layout: default
title: Customization
nav_order: 4
---
